### ISSUE TITLE
Autofill does not work

### ISSUE THREAD

**Issue by cyl02** [jvaglivelo/iOS-Supreme-Bot#5]
**Describe the bug**
Autofill does not work

**To Reproduce**
1. I  Go to have gone to edit Supreme.swift, with my data name, phone ...
2. Click on 'Run.'
3. Does not fill automatically

**Expected behavior**
I have edited the Supreme.swift and it does not automatically fill in the checkout

**Screenshots**
n/A

**Device Details (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - iOS Version: 13.3.3

**Additional context**
I also need you to explain how keywords work.

Thank you very much and I hope a reply soon

**Comment by jvaglivelo** [comment]
Fixed in the latest commit. It looks like everything was working but the CVV. Supreme seems to have removed the 'id' tag from the CVV input so I switched it to the 'name' tag. The 'name' tag does have a random name so it is likely this will be changed weekly. It would be best to implement a method to read the form elements.
